/** Design reminder — broker conversation page uses tactical dark panels, generous spacing, and explicit internal-use boundaries. */
import { Copy, Mic2, PauseCircle, ShieldCheck } from "lucide-react";
import TrainingShell from "@/components/TrainingShell";

const mirrors = [["We’re handling it in-house.", "In-house?"], ["I don’t know about the liability.", "The liability?"], ["I’ve heard this pitch before.", "Heard it before?"], ["My clients wouldn’t go for it.", "Wouldn’t go for it?"]];
const questions = ["How are you handling refund requests right now without overloading your team?", "What is the biggest concern in allowing an outside firm to touch a client’s entry?", "What would have to be true for a partnership like this to be worth your time?", "How am I supposed to get in front of your clients without it looking like I went around you?"];

export default function BrokerScript() { return <TrainingShell eyebrow="03 / BROKER PARTNERSHIP SCRIPT · APPROVED WORDING REQUIRED"><main id="top">
  <section className="academy-hero script-hero"><div><p className="academy-kicker">BROKER PARTNERSHIP PROGRAM</p><h1>Broker cold-call <span>conversation playbook.</span></h1><p className="academy-lede">A tactical empathy framework for starting a broker conversation without sounding like another generic recovery pitch.</p><div className="academy-actions"><a href="#opener">Start with the opener</a><a className="ghost" href="#objections">Jump to objections</a></div></div><div className="academy-hero-card voice"><Mic2 size={26} /><span>DELIVERY MODE</span><strong>Slow. Low. Downward.</strong><p>Coach the pauses as hard as the words. Silence is part of the technique.</p></div></section>
  <nav className="academy-subnav"><a href="#opener">Opener</a><a href="#ninety">90 seconds</a><a href="#mirrors">Mirrors</a><a href="#questions">Questions</a><a href="#objections">Objections</a><a href="#voicemail">Voicemail</a></nav>
  <section id="opener" className="academy-section pale"><p className="academy-kicker dark">01 / PERMISSION-BASED OPENER</p><h2>Earn the right to continue.</h2><div className="academy-script-stack"><article><span>OPEN</span><blockquote>“[Name], it’s [Rep Name]. I’m calling you cold, so I’m guessing this is a terrible time?”</blockquote><p>Stop. Let the person say “no, go ahead” or “what’s this about.” Do not race into the pitch.</p></article><article className="featured"><span>ACCUSATION AUDIT</span><blockquote>“You have probably had several refund firms call this month, you have already decided none are getting near your clients, and the last thing you need is someone without the right authority creating a problem.”</blockquote><p>Name the likely resistance before it becomes a weapon. Use only currently approved language.</p></article><article><span>FLIP THE FRAME</span><blockquote>“That is why I am calling licensed brokers instead of calling importers behind your back.”</blockquote><p>Pause. The point is relationship protection, not a promise about a program or outcome.</p></article></div></section>
  <section id="ninety" className="academy-section dark"><p className="academy-kicker">02 / THE NINETY SECONDS</p><h2>Label the operational pain—<br />not just the opportunity.</h2><div className="academy-grid-three dark-grid"><article><span>CONTEXT</span><p>Some importer conversations may require action and professional review. The broker may already be fielding those questions.</p></article><article><span>LABEL THE PAIN</span><p>“It sounds like the challenge is not whether requests exist. It is whether your team wants to absorb a new workload at volume.”</p></article><article><span>PARTNERSHIP FRAME</span><p>“The authorized team handles the process, you keep the client relationship, and you remain involved.”</p></article></div></section>
  <section id="mirrors" className="academy-section"><p className="academy-kicker dark">03 / MIRRORS</p><h2>Repeat their last two or three words—then stop.</h2><div className="academy-mirror-grid">{mirrors.map(([theySay, mirror]) => <article key={theySay}><div><span>THEY SAY</span><p>{theySay}</p></div><PauseCircle size={20} /><div><span>YOU MIRROR</span><strong>{mirror}</strong></div></article>)}</div></section>
  <section id="questions" className="academy-section pale"><p className="academy-kicker dark">04 / CALIBRATED QUESTIONS</p><h2>Replace the pitch with “how” and “what.”</h2><div className="academy-question-grid">{questions.map((question, index) => <article key={question}><span>0{index + 1}</span><blockquote>“{question}”</blockquote></article>)}</div><div className="academy-callout"><ShieldCheck size={20} /><p><strong>The gold question:</strong> “How am I supposed to get in front of your clients without it looking like I went around you?” When the broker solves this with you, the conversation becomes collaborative.</p></div></section>
  <section id="objections" className="academy-section dark"><p className="academy-kicker">05 / OBJECTION HANDLING</p><h2>Never lead with “but.”<br />Label first.</h2><div className="academy-objection-stack">{[["We already do this in-house.","It sounds like you have the capability and are not looking to outsource competence.","How does a supported workflow land if the question is bandwidth rather than capability?"],["What is your fee?", "That is the right question. I would rather show current approved information in the appropriate review than throw out a cold-call number.", "Would it be unreasonable to put fifteen minutes on the calendar for an approved workflow discussion?"],["Just send information.","I can—but a generic document can sit in an inbox without context.","Would fifteen minutes make the follow-up relevant to the broker’s book and process?"],["I’m not interested.","It seems like the timing may be wrong, more than the idea.","Is the concern the value proposition, workload, or a third party near the client relationship?"]].map(([objection,label,question], index) => <article key={objection}><header><span>0{index + 1} / OBJECTION</span><h3>“{objection}”</h3></header><div><p><b>Label:</b> {label}</p><p><b>Calibrated question:</b> {question}</p></div></article>)}</div></section>
  <section id="voicemail" className="academy-section"><p className="academy-kicker dark">06 / CLOSE AND VOICEMAIL</p><h2>Binary. Specific. Never open-ended.</h2><div className="academy-list-columns"><article><span>CLOSE</span><blockquote>“I have Thursday at 10 or Friday at 2. Which one is easier to protect?”</blockquote><p>Do not end with “let’s connect.” Offer two clear doors and document the agreed follow-up.</p></article><article><span>VOICEMAIL</span><blockquote>“[Name], [Rep Name], [phone]. I’m calling licensed brokers—not importers—about potential conversations involving their clients. The authorized team handles the workflow, you keep the relationship, and you remain involved. I’ll try you [day].”</blockquote><p>Keep it brief, factual, and within approved wording.</p></article></div><a className="academy-print" href="#top"><Copy size={15} /> Copy this framework into the approved content process</a></section>
</main></TrainingShell>; }
