/** Design reminder — business-owner script: internal command language, clear discovery stages, and no unsupported claims. */
import { ArrowRight, ClipboardCheck, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import TrainingShell from "@/components/TrainingShell";

const discovery = [
  ["Import activity", "Does the company manage imported goods directly, or does it coordinate through a customs broker?"],
  ["Process owner", "Who oversees import operations, purchasing, customs documentation, or inbound logistics?"],
  ["Documentation path", "Does the right team know where entry summaries or internal import records are maintained?"],
  ["Current resource", "Is there a licensed customs broker, trade professional, or internal resource who supports the process today?"],
  ["Permission", "Would the right contact be open to reviewing current approved information with a qualified specialist?"],
];

export default function BusinessScript() { return <TrainingShell eyebrow="07 / BUSINESS-OWNER SCRIPT · APPROVED INTERNAL WORDING"><main id="top">
  <section className="academy-hero script-hero"><div><p className="academy-kicker">BUSINESS CONVERSATION</p><h1>Open with process.<br /><span>Not a promise.</span></h1><p className="academy-lede">A business-owner conversation path for identifying process ownership, creating relevance, and arranging a responsible specialist handoff.</p><div className="academy-actions"><a href="#gatekeeper">Start with the gatekeeper</a><a className="ghost" href="#discovery">Discovery questions</a></div></div><div className="academy-hero-card voice"><ClipboardCheck size={26} /><span>CONVERSATION OBJECTIVE</span><strong>Locate the right owner. Clarify the process. Obtain permission for the next step.</strong><p>Do not determine eligibility, quote results, describe legal outcomes, discuss fees, or create timing expectations.</p></div></section>
  <nav className="academy-subnav"><a href="#gatekeeper">Gatekeeper</a><a href="#decision-maker">Decision maker</a><a href="#discovery">Discovery</a><a href="#positioning">Positioning</a><a href="#close">Close</a><a href="#boundaries">Boundaries</a></nav>
  <section id="gatekeeper" className="academy-section pale"><p className="academy-kicker dark">01 / GATEKEEPER</p><h2>Ask for the owner of the process.</h2><div className="academy-script-stack"><article><span>OPEN</span><blockquote>“Hi, this is [Your Name] with Tariff Refund Agency. Could I speak with the person who handles importing, customs documentation, or inbound purchasing for your company?”</blockquote><p>Lead with the role you need—not a result. Keep the first exchange concise and respectful.</p></article><article className="featured"><span>IF ASKED WHAT THIS IS ABOUT</span><blockquote>“I’m calling to see whether the appropriate person would be open to current approved information about an import-process review. I only need a moment with the person who owns that process.”</blockquote><p>Do not introduce legal, tariff, deadline, recovery, funding, fee, or eligibility statements unless you are using the current owner-approved content.</p></article></div></section>
  <section id="decision-maker" className="academy-section"><p className="academy-kicker dark">02 / DECISION MAKER</p><h2>Confirm relevance before the explanation.</h2><div className="academy-script-stack"><article><span>OPEN</span><blockquote>“Hi [Name], this is [Rep Name] with Tariff Refund Agency. I’ll be brief—does your team manage imports directly, or do you coordinate that work through a broker?”</blockquote><p>Pause and listen. The response determines whether you continue, ask for a colleague, or route to the broker pathway.</p></article><article><span>RELEVANCE FRAME</span><blockquote>“I work with companies that manage imported products. I’m calling to see whether a short conversation with the appropriate approved resource would be useful for your team.”</blockquote><p>Use the current version of this wording. Never turn relevance into a predicted result.</p></article></div></section>
  <section id="discovery" className="academy-section dark"><p className="academy-kicker">03 / DISCOVERY</p><h2>Ask the facts.<br />Do not fill in the gaps.</h2><div className="academy-qualifier-list dark-list">{discovery.map(([title, question], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{question}</p></div><ShieldCheck size={20} /></article>)}</div><Link className="academy-inline-link" href="/qualifier">Open the five-question qualifier <ArrowRight size={15} /></Link></section>
  <section id="positioning" className="academy-section pale"><p className="academy-kicker dark">04 / SAFE POSITIONING</p><h2>Describe the handoff—<br />not the outcome.</h2><div className="academy-grid-three"><article><span>WHAT YOU MAY SAY</span><h3>“The team can explain the review process.”</h3><p>Position a qualified resource as the next place for fact-specific questions.</p></article><article><span>WHAT YOU MAY SAY</span><h3>“The right person can review current approved materials.”</h3><p>Use updated education resources; note the version and approved owner where required.</p></article><article><span>WHAT YOU MAY SAY</span><h3>“I can document your question for a follow-up.”</h3><p>Capture the issue accurately rather than offering a speculative answer.</p></article></div></section>
  <section id="close" className="academy-section"><p className="academy-kicker dark">05 / CLOSE</p><h2>Offer a clear, controlled next step.</h2><div className="academy-list-columns"><article><span>INTRODUCTION</span><blockquote>“Would a short introductory conversation with the appropriate approved resource be useful for the right person on your team?”</blockquote><p>Use permission, give the person a clear choice, and record the requested follow-up.</p></article><article><span>APPROVED RESOURCE</span><blockquote>“Would you prefer that I send the current approved overview for the right person to review first?”</blockquote><p>Do not substitute an old link or an unapproved document for the current source.</p></article></div></section>
  <section id="boundaries" className="academy-section dark"><p className="academy-kicker">06 / STOP CONDITIONS</p><h2>Know when to pause and escalate.</h2><div className="academy-callout dark-note"><ShieldCheck size={20} /><p><strong>Escalate immediately:</strong> requests for specific legal or customs interpretation; refund or recovery estimates; filing advice; deadlines; fees; funding; evidence of eligibility; or a prediction about any outcome. The agent’s job is a precise handoff, not an improvised answer.</p></div></section>
</main></TrainingShell>; }
