/** Design reminder — category research is a disciplined operational catalog, not a decorative card wall. */
import { useMemo, useState, type CSSProperties } from "react";
import { ArrowRight, Search } from "lucide-react";
import TrainingShell from "@/components/TrainingShell";
import { categories, sectors } from "@/lib/trainingData";

export default function Categories() { const [filter, setFilter] = useState("All"); const [query, setQuery] = useState(""); const visible = useMemo(() => categories.filter((item) => (filter === "All" || item.sector === filter) && `${item.title} ${item.copy}`.toLowerCase().includes(query.toLowerCase())), [filter, query]); return <TrainingShell eyebrow="04 / PRIORITY CATEGORY RESEARCH · PROSPECTING SIGNALS ONLY"><main id="top">
  <section className="academy-hero categories-hero"><div><p className="academy-kicker">CATEGORY EXPLORER</p><h1>18 priority business <span>categories.</span></h1><p className="academy-lede">Use these categories to concentrate research and open a relevant conversation. Category fit is not a final eligibility determination.</p></div><div className="academy-hero-card"><span>RESEARCH STANDARD</span><strong>Start broad. Verify the process. Route the records.</strong><p>Use the qualifier after a category signal appears; do not infer a duty, recovery, filing path, or outcome.</p></div></section>
  <section className="academy-section category-page"><div className="academy-category-tools"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products or categories" /></label><div>{sectors.map((sector) => <button key={sector} className={sector === filter ? "active" : ""} onClick={() => setFilter(sector)}>{sector}</button>)}</div></div><div className="academy-category-grid">{visible.map((item, index) => <article key={item.title} style={{ "--signal": item.tone } as CSSProperties}><header><b>{item.code}</b><span>{String(categories.indexOf(item) + 1).padStart(2, "0")}</span></header><em>{item.sector}</em><h2>{item.title}</h2><p>{item.copy}</p><a href="/qualifier">Use qualifier <ArrowRight size={14} /></a></article>)}</div>{visible.length === 0 && <p className="academy-empty">No category matches that search. Try a broader product or sector phrase.</p>}</section>
</main></TrainingShell>; }
