/** Design reminder — Comp Plan route is a direct, image-led agent reference: the plan is visible immediately and supporting sections stay concise. */
import { Calculator } from "lucide-react";
import TrainingShell from "@/components/TrainingShell";

const planImage = "https://github.com/mikehinsvark/tariffrefunds-vip/releases/download/static-assets-v1/pasted_file_Hw6m2s_.CFFEB943-CA39-48B6-92A7-9F549AEB0747.webp";
const titleShares = [["SAP", "71.5%", "Senior Agency Partner"], ["AP", "57.1%", "Agency Partner"], ["EMD", "50.0%", "Executive Marketing Director"], ["SMD", "45.0%", "Senior Marketing Director"], ["MD", "40.0%", "Marketing Director"]];
const overrides = [["Generation 1", "10.0%"], ["Generation 2", "5.0%"], ["Generation 3", "4.0%"], ["Generation 4", "3.0%"], ["Generation 5", "2.0%"], ["Generation 6", "1.0%"]];

export default function CompPlan() {
  return <TrainingShell eyebrow="09 / COMP PLAN" showAlert={false} footerNote="Dreams Tariff Refund Comp Plan · Agent resource library"><main id="top">
    <section className="academy-hero"><div><p className="academy-kicker">COMPENSATION REFERENCE</p><h1>See the plan.<br /><span>Know the path.</span></h1><p className="academy-lede">A visual overview of direct compensation, title shares, overrides, and bonus pools for Dreams agents.</p><div className="academy-actions"><a href="#plan">View comp plan</a><a className="ghost" href="#formula">Comp formula</a></div></div><div className="academy-hero-card"><Calculator size={26} /><span>COMPENSATION OVERVIEW</span><strong>One plan.<br />One shared reference.</strong><p>Review the structure, examples, and bonus-pool view in one place.</p></div></section>
    <nav className="academy-subnav"><a href="#plan">Comp plan</a><a href="#formula">Formula</a><a href="#titles">Title shares</a><a href="#overrides">Overrides</a><a href="#pools">Bonus pools</a><a href="#questions">Plan questions</a></nav>
    <section id="plan" className="academy-section pale comp-plan-image-section"><p className="academy-kicker dark">01 / COMP PLAN</p><img className="comp-plan-image" src={planImage} alt="Dreams Tariff Refund Comp Plan" /></section>
    <section id="formula" className="academy-section dark"><p className="academy-kicker">02 / CALCULATOR MODEL</p><h2>Understand the sequence<br />before opening the calculator.</h2><div className="academy-rate-grid"><article><span>CLIENT FEE BASIS</span><strong>20%</strong><p>Percentage of refund volume used in the plan model.</p></article><article><span>MONTHLY PAYOUT POOL</span><strong>35%</strong><p>Percentage of the calculated fee used for the payout pool.</p></article><article><span>DIRECT COMP MODEL</span><strong>Fee × payout pool × title share</strong><p>The structure used to show direct compensation examples.</p></article></div><blockquote className="academy-quote">Start with the refund volume, apply the client fee, calculate the payout pool, then apply the title share and any qualified bonus elements.</blockquote></section>
    <section id="titles" className="academy-section"><p className="academy-kicker dark">03 / TITLE SHARE REFERENCE</p><h2>Title shares at a glance.</h2><div className="academy-title-table">{titleShares.map(([title, share, description]) => <article key={title}><b>{title}</b><strong>{share}</strong><span>{description}</span><em>Share of payout pool</em></article>)}</div></section>
    <section id="overrides" className="academy-section pale"><p className="academy-kicker dark">04 / GENERATIONAL OVERRIDES</p><h2>See the generation path.</h2><div className="academy-override-grid">{overrides.map(([generation, rate]) => <article key={generation}><span>{generation}</span><strong>{rate}</strong><p>Override percentage shown in the Comp Plan.</p></article>)}</div></section>
    <section id="pools" className="academy-section dark"><p className="academy-kicker">05 / BONUS-POOL GUIDE</p><h2>Bonus pools<br />at a glance.</h2><div className="academy-grid-three dark-grid"><article><span>PERSONAL PRODUCTION</span><h3>Personal Pool</h3><p>3+ personal sales and $1M+ personal volume. Pool example shown as 1% of the company payout pool.</p></article><article><span>AGENCY PARTNER</span><h3>Agency Partner Pool</h3><p>20+ agency sales and $10M+ agency volume. Pool example shown as 1%.</p></article><article><span>SENIOR AGENCY PARTNER</span><h3>Senior Partner Pool</h3><p>100+ total sales and $50M+ total volume. Pool example shown as 1%.</p></article></div></section>
    <section id="questions" className="academy-section"><p className="academy-kicker dark">06 / PLAN QUESTIONS</p><h2>Open the plan.<br />Then ask the next question.</h2><div className="academy-script-stack"><article><span>AGENT TALK TRACK</span><blockquote>“Let’s pull up the Comp Plan and walk through the section that applies to your question.”</blockquote><p>Use the plan image as the shared starting point for title, override, and bonus-pool conversations.</p></article></div></section>
  </main></TrainingShell>;
}
