/** Design reminder — controlled comp reference: dense operational data panels, version visibility, and strict no-quote disclosures. */
import { AlertTriangle, BadgeCheck, Calculator, ShieldCheck } from "lucide-react";
import TrainingShell from "@/components/TrainingShell";

const titleShares = [["SAP", "71.5%", "Senior Agency Partner"], ["AP", "57.1%", "Agency Partner"], ["EMD", "50.0%", "Executive Marketing Director"], ["SMD", "45.0%", "Senior Marketing Director"], ["MD", "40.0%", "Marketing Director"]];
const overrides = [["Generation 1", "10.0%"], ["Generation 2", "5.0%"], ["Generation 3", "4.0%"], ["Generation 4", "3.0%"], ["Generation 5", "2.0%"], ["Generation 6", "1.0%"]];

export default function CompPlan() { return <TrainingShell eyebrow="09 / COMP PLAN AND CALCULATOR REFERENCE · INTERNAL CONTROLLED CONTENT"><main id="top">
  <section className="academy-hero"><div><p className="academy-kicker">COMPENSATION REFERENCE</p><h1>Reference the plan.<br /><span>Do not quote from memory.</span></h1><p className="academy-lede">A controlled internal reference for understanding the calculator’s inputs, title shares, bonus assumptions, and escalation rules. This is not a promise or projection.</p><div className="academy-actions"><a href="#formula">Comp formula</a><a className="ghost" href="#controls">Content controls</a></div></div><div className="academy-hero-card"><Calculator size={26} /><span>VERSION CONTROL</span><strong>Internal Reference · Confirm current plan before every external use.</strong><p>Values below are educational source settings only. Owner approval, effective dates, eligibility, and plan terms must be confirmed before discussion.</p></div></section>
  <nav className="academy-subnav"><a href="#controls">Controls</a><a href="#formula">Formula</a><a href="#titles">Title shares</a><a href="#overrides">Overrides</a><a href="#pools">Bonus pools</a><a href="#escalate">Escalate</a></nav>
  <section id="controls" className="academy-section pale"><p className="academy-kicker dark">01 / CONTENT CONTROL</p><h2>This page teaches the model.<br />It does not make a guarantee.</h2><div className="academy-reference-banner"><BadgeCheck size={25} /><div><span>INTERNAL REFERENCE STATUS</span><strong>Source: Calculator handoff · Version/date must be owner-confirmed before agent use.</strong><p>Do not present a calculator output, title share, pool value, threshold, fee, or override as a personal income promise. Treat every output as an internal educational scenario pending current plan verification.</p></div></div><div className="academy-grid-three"><article><span>USE INTERNALLY</span><h3>Learn the vocabulary</h3><p>Understand fee basis, payout pool, title share, referral mechanics, generation concepts, and bonus-pool assumptions.</p></article><article><span>VERIFY FIRST</span><h3>Confirm the current plan</h3><p>Use only the current owner-approved plan version, effective date, qualification rules, disclosures, and calculator settings.</p></article><article><span>ESCALATE EXTERNALLY</span><h3>Route compensation questions</h3><p>Agents should direct compensation-specific questions to the approved plan owner or authorized resource.</p></article></div></section>
  <section id="formula" className="academy-section dark"><p className="academy-kicker">02 / CALCULATOR MODEL</p><h2>Understand the sequence<br />before opening the calculator.</h2><div className="academy-rate-grid"><article><span>CLIENT FEE BASIS</span><strong>20%</strong><p>Reference setting shown in the calculator source as a percentage of refund volume.</p></article><article><span>MONTHLY PAYOUT POOL</span><strong>35%</strong><p>Reference setting shown in the calculator source as a percentage of the calculated fee.</p></article><article><span>DIRECT COMP MODEL</span><strong>Fee × payout pool × title share</strong><p>Each component is a controlled plan setting, not an agent-created estimate.</p></article></div><blockquote className="academy-quote">The calculator is a scenario tool: start with a controlled input, apply the reference fee basis, calculate the payout pool, then apply the confirmed title share and any separately qualified elements.</blockquote></section>
  <section id="titles" className="academy-section"><p className="academy-kicker dark">03 / TITLE SHARE REFERENCE</p><h2>Title shares are a plan setting.</h2><div className="academy-title-table">{titleShares.map(([title,share,description]) => <article key={title}><b>{title}</b><strong>{share}</strong><span>{description}</span><em>Reference share of payout pool</em></article>)}</div><div className="academy-callout"><AlertTriangle size={20} /><p><strong>Do not improvise:</strong> title qualification, conversion, rank, share, timing, vesting, or payout interpretations must come from the current approved plan—not this training page alone.</p></div></section>
  <section id="overrides" className="academy-section pale"><p className="academy-kicker dark">04 / GENERATIONAL OVERRIDES</p><h2>Learn the structure.<br />Verify the entitlement.</h2><div className="academy-override-grid">{overrides.map(([generation, rate]) => <article key={generation}><span>{generation}</span><strong>{rate}</strong><p>Reference rate shown in the calculator source. Confirm title, qualification, agency status, and plan version before applying.</p></article>)}</div><div className="academy-callout"><ShieldCheck size={20} /><p><strong>Role limitation:</strong> The calculator source identifies certain override mechanics as available to specified agency titles. That source setting is not proof of an individual’s eligibility or payment.</p></div></section>
  <section id="pools" className="academy-section dark"><p className="academy-kicker">05 / BONUS-POOL GUIDE</p><h2>Pool assumptions require<br />the current plan document.</h2><div className="academy-grid-three dark-grid"><article><span>PERSONAL PRODUCTION</span><h3>Reference threshold</h3><p>Calculator source scenario: 3+ personal sales and $1M+ personal volume. Pool is shown as 1% of company payout pool.</p></article><article><span>AGENCY PARTNER</span><h3>Reference threshold</h3><p>Calculator source scenario: specified agency title plus 20+ agency sales and $10M+ agency volume. Pool is shown as 1%.</p></article><article><span>SENIOR AGENCY PARTNER</span><h3>Reference threshold</h3><p>Calculator source scenario: senior title plus 100+ total sales and $50M+ total volume. Pool is shown as 1%.</p></article></div><div className="academy-callout dark-note"><AlertTriangle size={20} /><p><strong>Scenario notice:</strong> pool allocation, qualifier counts, sales volume, rates, and thresholds in any calculator output are assumptions. They are not compensation projections or a promise of qualification.</p></div></section>
  <section id="escalate" className="academy-section"><p className="academy-kicker dark">06 / SAFE AGENT RESPONSE</p><h2>When asked about income, route—not reassure.</h2><div className="academy-script-stack"><article><span>APPROVED RESPONSE FRAME</span><blockquote>“I can show you the internal reference page, but I do not want to give you an incomplete answer. The current plan, qualification rules, and any individual scenario need to be confirmed through the approved compensation resource.”</blockquote><p>Record the question and route it to the current plan owner. Never substitute a past calculator result for the current plan.</p></article></div></section>
</main></TrainingShell>; }
