/** Design reminder — contact research is a disciplined internal evidence workflow, with role hierarchy and minimum-data controls. */
import { ArrowRight, ContactRound, FileCheck2, SearchCheck, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import TrainingShell from "@/components/TrainingShell";

const businessRoles = [["Primary", "Owner · CEO · President · Managing Director"], ["Secondary", "CFO · Controller · VP of Finance · Director of Finance"], ["Tertiary", "VP of Operations · Supply Chain Director · Import/Export Manager · Logistics Manager"]];
const brokerRoles = [["Primary", "Owner · Principal Broker · Managing Partner"], ["Secondary", "Operations Manager · Client Services Director"], ["Tertiary", "Licensed Broker on Staff · Compliance Officer"]];
const researchSteps = [["01", "Start with the company", "Use the company website, existing approved CRM data, and permitted business directories to understand operations and product cues."], ["02", "Map the process", "Identify references to import operations, sourcing, customs, distribution, supply chain, or inbound purchasing."], ["03", "Find the role", "Prioritize process ownership and finance/operations influence over title guessing."], ["04", "Prepare the route", "Document only the facts needed to make a respectful, relevant first contact and the approved next step."]];

export default function ContactResearch() { return <TrainingShell eyebrow="08 / CONTACT RESEARCH · APPROVED SOURCES AND MINIMUM NECESSARY DATA"><main id="top">
  <section className="academy-hero"><div><p className="academy-kicker">ACCOUNT MAPPING</p><h1>Find the role.<br /><span>Respect the route.</span></h1><p className="academy-lede">A controlled research workflow for identifying process owners, preparing credible first contact, and protecting customer and partner relationships.</p><div className="academy-actions"><a href="#hierarchy">Contact hierarchy</a><a className="ghost" href="#workflow">Research workflow</a></div></div><div className="academy-hero-card"><ContactRound size={26} /><span>RESEARCH STANDARD</span><strong>Use the minimum information needed to make the next conversation relevant.</strong><p>Do not obtain, store, or use sensitive or restricted data outside approved systems, permissions, and privacy practices.</p></div></section>
  <nav className="academy-subnav"><a href="#hierarchy">Hierarchy</a><a href="#workflow">Workflow</a><a href="#sources">Sources</a><a href="#gatekeeper">Gatekeeper</a><a href="#record">CRM record</a><a href="#boundaries">Boundaries</a></nav>
  <section id="hierarchy" className="academy-section pale"><p className="academy-kicker dark">01 / WHO TO CONTACT</p><h2>Start with responsibility—<br />not job-title volume.</h2><div className="academy-compare"><article><ContactRound size={22} /><span>BUSINESS OWNER CALLS</span><h3>Importer contact hierarchy</h3><div className="academy-role-list">{businessRoles.map(([tier, roles]) => <p key={tier}><b>{tier}</b>{roles}</p>)}</div></article><article className="dark-card"><ContactRound size={22} /><span>CUSTOMS BROKER CALLS</span><h3>Broker contact hierarchy</h3><div className="academy-role-list">{brokerRoles.map(([tier, roles]) => <p key={tier}><b>{tier}</b>{roles}</p>)}</div></article></div></section>
  <section id="workflow" className="academy-section"><p className="academy-kicker dark">02 / RESEARCH WORKFLOW</p><h2>Research is preparation—<br />not proof.</h2><div className="academy-process">{researchSteps.map(([number,title,copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="academy-callout"><SearchCheck size={20} /><p><strong>Category signal:</strong> Use the 18-category explorer to sharpen your research terms. A company, product, role, or shipment signal is never a conclusion about eligibility, duty, recovery, deadline, or outcome.</p></div></section>
  <section id="sources" className="academy-section dark"><p className="academy-kicker">03 / APPROVED SOURCE TYPES</p><h2>Work from visible, permitted, and relevant information.</h2><div className="academy-grid-three dark-grid"><article><span>OWNED DATA</span><h3>Approved CRM records</h3><p>Review prior notes, consent status, account owner, and previously documented handoff requests before making contact.</p></article><article><span>PUBLIC BUSINESS CONTEXT</span><h3>Company and trade presence</h3><p>Use public company pages, published product catalogues, trade association listings, and event information under current policy.</p></article><article><span>ROLE DISCOVERY</span><h3>Professional identifiers</h3><p>Use permitted public professional sources to identify a relevant operating role. Do not scrape restricted data or bypass access controls.</p></article></div></section>
  <section id="gatekeeper" className="academy-section pale"><p className="academy-kicker dark">04 / GATEKEEPER NAVIGATION</p><h2>Be specific, calm, and useful.</h2><div className="academy-script-stack"><article><span>ASK FOR THE ROLE</span><blockquote>“Could you point me to the person who handles import operations, customs documentation, or inbound purchasing?”</blockquote><p>Specificity is more respectful than demanding “the owner” when process ownership is the real goal.</p></article><article><span>LEAVE A CLEAN MESSAGE</span><blockquote>“Please let [Name] know I called about an import-process conversation. I will leave my name and number, and I will also send the current approved overview if that is helpful.”</blockquote><p>Never ask a gatekeeper to communicate a recovery, deadline, eligibility, fee, legal, or outcome claim that the agent is not authorized to make.</p></article></div></section>
  <section id="record" className="academy-section"><p className="academy-kicker dark">05 / CRM-READY PREPARATION</p><h2>Leave the next person a useful record.</h2><div className="academy-grid-three"><article><FileCheck2 size={21} /><h3>Account facts</h3><p>Company, relevant public operating context, current relationship status, source type, and account owner.</p></article><article><FileCheck2 size={21} /><h3>Contact route</h3><p>Role, public business contact method if approved, decision authority, gatekeeper result, and stated preferences.</p></article><article><FileCheck2 size={21} /><h3>Next action</h3><p>Requested resource, permission status, scheduled follow-up, escalation question, and source-content version used.</p></article></div><Link href="/business-script" className="academy-inline-link">Practice the business script <ArrowRight size={15} /></Link></section>
  <section id="boundaries" className="academy-section dark"><p className="academy-kicker">06 / DATA BOUNDARY</p><h2>Respect privacy and the relationship.</h2><div className="academy-callout dark-note"><ShieldCheck size={20} /><p><strong>Do not:</strong> request confidential broker client lists, collect unnecessary sensitive personal data, bypass access controls, add unverified contact data to the CRM, or use research to imply a legal, financial, eligibility, or outcome conclusion.</p></div></section>
</main></TrainingShell>; }
