/** Design reminder — rich internal field guide: clear hierarchy, Recovery Gold actions, and compliance-forward learning. */
import { Link } from "wouter";
import { ArrowRight, BriefcaseBusiness, Check, FileSearch, MapPinned, ShieldCheck, UsersRound } from "lucide-react";
import TrainingShell from "@/components/TrainingShell";

const brokerSteps = ["Offer a co-branded educational briefing.", "Do not request a confidential client list.", "Keep the broker involved and protect the relationship.", "Offer private document-readiness appointments through approved channels.", "Use approved follow-up and specialist escalation." ];
const importerSteps = ["Map trade lanes and prospect clusters.", "Identify company names from permitted, approved research sources.", "Locate the responsible finance, trade, or supply-chain contact.", "Verify process ownership and route records review to authorized specialists." ];
const campaigns = ["Bring Your 7501 readiness clinic", "Tariff refund town hall", "Broker-approved client re-engagement", "Trade-show exhibitor research", "Tariff-exposure signals", "Importer look-alikes"];

export default function FieldGuide() {
  return <TrainingShell eyebrow="02 / RESTORED FIELD GUIDE · INTERNAL USE ONLY"><main id="top">
    <section className="academy-hero guide-hero"><div><p className="academy-kicker">PROSPECTING SYSTEM</p><h1>Find the businesses behind the <span>import process.</span></h1><p className="academy-lede">A restored research and partnership playbook for gateways, customs-broker relationships, trade associations, and verified importer conversations.</p><div className="academy-actions"><a href="#broker-path">Broker pathway <ArrowRight size={16} /></a><a className="ghost" href="#guardrails">Guardrails</a></div></div><div className="academy-hero-card"><MapPinned size={25} /><span>CORE STRATEGY</span><strong>Use the gateway to find the ecosystem. Use process ownership to find the right next conversation.</strong><p>Location and shipment signals are research inputs—not proof of eligibility, duty paid, recovery, deadline, or outcome.</p></div></section>
    <nav className="academy-subnav" aria-label="Field-guide sections"><a href="#ecosystem">Ecosystem</a><a href="#broker-path">Broker partners</a><a href="#importers">Direct importers</a><a href="#campaigns">Campaigns</a><a href="#launch">30-day plan</a><a href="#guardrails">Guardrails</a></nav>
    <section id="ecosystem" className="academy-section pale"><p className="academy-kicker dark">01 / RESEARCH MODEL</p><h2>Geography is powerful—<br />but only half the strategy.</h2><p className="section-intro">Ports, border crossings, cargo airports, warehouses, forwarders, and foreign-trade-zone clusters can concentrate relevant activity. The company that manages the import process may be located far from the gateway.</p><div className="academy-compare"><article><MapPinned size={22} /><span>WHERE FREIGHT ENTERS</span><h3>Gateway ecosystem</h3><p>Ports, land crossings, cargo airports, customs brokers, forwarders, warehouses, and trade clusters are useful referral and research environments.</p><b>Excellent for relationship multipliers</b></article><article className="dark-card"><FileSearch size={22} /><span>WHO MAY HAVE PAID</span><h3>Importer of Record</h3><p>The company shown on the customs entry may be responsible for payment and compliance. Confirm facts through the approved review process.</p><b>Essential for direct qualification</b></article></div><div className="academy-table"><div><b>Highest leverage</b><span>Licensed customs brokers and verified process owners</span></div><div><b>High</b><span>Seaports, land crossings, trade associations, and industry clusters</span></div><div><b>Use with care</b><span>Passenger hubs and generic geography without operational verification</span></div></div></section>
    <section id="broker-path" className="academy-section dark"><p className="academy-kicker">02 / HIGHEST-LEVERAGE PLAY</p><h2>Build customs-broker partnerships first.</h2><p className="section-intro">One productive partner relationship can create an ethical, relationship-protective education path without asking for confidential client data.</p><div className="academy-steps">{brokerSteps.map((step, index) => <article key={step}><span>0{index + 1}</span><Check size={18} /><p>{step}</p></article>)}</div><blockquote className="academy-quote">“We do not need your client list. Let us provide a co-branded educational briefing. You retain the relationship and remain involved. Interested importers opt in directly.”</blockquote><Link href="/broker-script" className="academy-inline-link">Open the complete broker call script <ArrowRight size={15} /></Link></section>
    <section id="importers" className="academy-section"><p className="academy-kicker dark">03 / DIRECT IMPORTER PROSPECTING</p><h2>Build a data-driven importer list.</h2><div className="academy-process">{importerSteps.map((step, index) => <article key={step}><span>0{index + 1}</span><h3>{["Map the lane", "Identify the company", "Find the right person", "Verify the payer"][index]}</h3><p>{step}</p></article>)}</div><div className="academy-callout"><ShieldCheck size={20} /><p><strong>Qualification rule:</strong> A consignee or shipment-data reference is a lead—not proof. Do not promise eligibility, timing, refunds, or a result. Route record review to authorized specialists.</p></div><div className="academy-list-columns"><article><h3>Decision-maker signals</h3><p>CFO or controller; trade-compliance leader; import manager; supply-chain or logistics leader; counsel; or owner/president for smaller operations.</p></article><article><h3>Five-question screen</h3><p>Ask about Importer-of-Record status, import activity, product categories, available entry documentation, and the broker that handled entries. Use current approved wording.</p></article></div></section>
    <section id="campaigns" className="academy-section pale"><p className="academy-kicker dark">04 / CREATIVE CAMPAIGNS</p><h2>Give prospects a useful reason to respond.</h2><p className="section-intro">The strongest offers lead with education and readiness. They do not make a recovery, timing, or eligibility promise.</p><div className="academy-grid-three">{campaigns.map((campaign, index) => <article key={campaign}><span>0{index + 1}</span><h3>{campaign}</h3><p>Use approved wording to invite a practical readiness conversation and document the appropriate next step.</p></article>)}</div></section>
    <section id="launch" className="academy-section dark"><p className="academy-kicker">05 / 30-DAY LAUNCH PLAN</p><h2>Run three motions at the same time.</h2><div className="academy-process four">{[["WEEK 1","Build the target universe","Segment partner, association, and research lists."],["WEEK 2","Launch partner outreach","Invite partners to an approved education briefing."],["WEEK 3","Launch importer outreach","Use readiness-first contact with a private review option."],["WEEK 4","Measure and scale","Track conversations, opt-ins, documented follow-ups, and specialist handoffs."]].map(([week,title,copy]) => <article key={week}><span>{week}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section id="guardrails" className="academy-section guardrail-section"><p className="academy-kicker dark">06 / GUARDRAILS</p><h2>Protect the importer, the broker, and the agent.</h2><div className="academy-grid-three">{[["Authorized submission","Authorized specialists and the appropriate importer or broker roles handle submissions under applicable procedures."],["Client confidentiality","Do not seek or use protected client information without proper authorization."],["Agent boundary","Do not prepare filings, interpret classifications, offer legal views, or make outcome promises."],["Fee disclosure","Use current approved private-service fee materials; do not speak for government procedures or costs."],["No blanket claims","Potential opportunities are not a determination. Do not generalize one fact pattern to all importers."],["Escalation","Route compensation, POA, data flow, program, deadline, and eligibility questions to qualified resources."]].map(([title,copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="academy-source-note">Source-guide material restored for internal training. Verify current policy, law, procedure, event, program, fee, and version details before using in a live conversation.</div></section>
  </main></TrainingShell>;
}
