/** Design reminder — overview is a concise multi-page command deck, using image-led orientation rather than a long scrolling curriculum. */
import { Link } from "wouter";
import { ArrowRight, BookOpen, BriefcaseBusiness, CircleHelp, Compass, Network, SearchCheck } from "lucide-react";
import TrainingShell from "@/components/TrainingShell";

const modules = [
  ["/field-guide", "02", "Field guide", "Restore the gateway, partnership, direct-importer, campaign, launch, and guardrail playbook.", BookOpen],
  ["/broker-script", "03", "Broker script", "Practice the permission opener, tactical empathy, calibrated questions, and partnership close.", BriefcaseBusiness],
  ["/categories", "04", "Category explorer", "Search all 18 priority categories, then use the qualifier to structure the handoff.", Network],
  ["/qualifier", "05", "Qualifier", "Use a five-question screen to organize facts without deciding the outcome.", SearchCheck],
  ["/objections", "06", "Objection practice", "Rehearse safe responses and escalation language for hard questions.", CircleHelp],
];
export default function Home() { return <TrainingShell eyebrow="01 / TRAINING COMMAND CENTER"><main id="top"><section className="academy-hero home-hero"><div><p className="academy-kicker">AGENT OPPORTUNITY FIELD GUIDE</p><h1>Use the right page<br />for the <span>right conversation.</span></h1><p className="academy-lede">A complete internal training website for researching prospects, building broker partnerships, preparing compliant conversations, and routing the next step.</p><div className="academy-actions"><Link href="/field-guide">Open field guide <ArrowRight size={16} /></Link><Link className="ghost" href="/broker-script">Broker script</Link></div></div><div className="academy-home-image"><img src="/manus-storage/01-hidden-refund-opportunity_22331b64.png" alt="Industrial trade route visual" /><div><span>RESTORED TRAINING LIBRARY</span><strong>Five routed learning pages. One controlled agent workflow.</strong></div></div></section><section className="academy-section overview-grid-section"><p className="academy-kicker dark">SELECT A TRAINING PAGE</p><h2>Move through the work—not one endless page.</h2><div className="academy-module-grid">{modules.map(([href, number, title, copy, Icon]) => { const ModuleIcon = Icon as typeof Compass; return <Link href={href as string} key={href as string}><article><span>{number as string}</span><ModuleIcon size={23} /><h3>{title as string}</h3><p>{copy as string}</p><b>Open page <ArrowRight size={14} /></b></article></Link>; })}</div></section><section className="academy-section dark overview-note"><p className="academy-kicker">CONTENT CONTROL</p><h2>Restore the curriculum.<br />Keep the boundary.</h2><p>Rich source-guide content is now organized into linked pages. It remains internal training material and must be paired with current approved resources before agents use claims, program specifics, legal or customs language, time-sensitive facts, costs, deadlines, or outcomes.</p></section></main></TrainingShell>; }
